### PR TITLE
Extract dragged sprites' drawables in screen space

### LINKED ISSUE #1782: Sprite size changes when dragging
### Expected Behavior

Dragged sprite should be the same as sprite on stage

### Actual Behavior

Sprite gets bigger when responsive UI is on
spritesizechange

### Steps to Reproduce

Drag the sprite

### Operating System and Browser

Windows 10 Chrome

### LINKED ISSUE #1894: Ghost effect does not remain when dragging
### Expected Behavior

Ghost effect does not remain when dragging

### Actual Behavior

Ghost effect does not remain, although all other graphic effects do

### Steps to Reproduce

Set ghost effect on the cat to non-zero
Drag the cat
ghostdrag

### Operating System and Browser
Windows 10 Chrome

### LINKED ISSUE #2388: Sprite size is not scaled for dragging on small stage
### Expected Behavior

_Please describe what should happen_
When you drag a sprite on the small stage it should be sized appropriately for the small stage.

### Actual Behavior

_Describe what actually happens_
Sprites are full size when dragged.
small-stage

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Drag a sprite when in small stage mode. It's easier to see with larger sprites.

### Operating System and Browser

macOS High Sierra version 10.13.4 (17E202) Firefox Quantum 60.0.1 (64-bit) and Chrome

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

Resolves https://github.com/LLK/scratch-render/issues/294
Resolves #2388
Resolves #1782
~~Resolves (no longer does) #1894~~
Resolves https://github.com/LLK/scratch-render/issues/657

### Proposed Changes

This PR updates the GUI to use the new `extractDrawableScreenSpace` method introduced in https://github.com/LLK/scratch-render/pull/568. In addition, it moves the "drag offset" math into the `Stage` container instead of leaving it to `extractDrawable`.

### Reason for Changes

This resolves the four bugs mentioned above.

### Test Coverage

Tested manually

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Linux
* [x] Firefox
* [x] Chrome

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [ ] Chrome 
 * [ ] Firefox 
 * [x] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

Android Phone
* [x] Firefox
* [x] Chrome

### CODE REVIEW

**Comment by benjiwheeler** [comment]
Blocked on https://github.com/LLK/scratch-render/pull/568 being merged, scheduling it in August (but could do earlier if it gets unblocked)

File: src/containers/stage.jsx [hunk 1]
```diff
@@ -304,25 +304,25 @@ class Stage extends React.Component {
         }
         this.setState({mouseDownTimeoutId: null});
     }
-    drawDragCanvas (drawableData) {
```
Comment (fsih) [inline src/containers/stage.jsx:307]: Add doc here?
