### PR TITLE
Fix default parameter text loading in English

### LINKED ISSUE #2544: Example inputs(like apple in join(apple)(banana)) aren't change while switching language
### Expected Behavior

They change to the correct language

### Actual Behavior

They NEVER
screenshot_2018-07-03-17-54-52-687_com android chrome
screenshot_2018-07-03-17-55-11-297_com android chrome
screenshot_2018-07-03-17-55-30-089_com android chrome

### Steps to Reproduce

Switching between languages

### Operating System and Browser

Android Chrome(I guess all?)

### LINKED ISSUE #5445: Default text in sensing and operator blocks always loads in English
### Expected Behavior

When the editor loads in a different language (e.g. due to browser language setting), the default text on the `ask` and text operator blocks should be translated.

### Actual Behavior

The default text is in English. Here's an example with the editor loading in Spanish:
screen shot 2018-12-17 at 9 33 31 am
screen shot 2018-12-17 at 9 33 53 am

If you switch to another language, they are translated when the new language loads. Here's the same blocks after switching to Italian:
screen shot 2018-12-17 at 9 37 52 am
screen shot 2018-12-17 at 9 38 15 am

And if you go back to Spanish afterwards, the default text **is** translated.

### Steps to Reproduce
Load the editor in a language other than English, either by setting the language in the browser, or by adding `?locale=es` to the URL to set the language (replace `es` by any language code).

### LINKED ISSUE #5489: Variable in blocks are not being translated
### Expected Behavior
Is expected to have some blocks translated to the selected languages - blocks itself is ok, but variable inside each blocks are not following same logic.

### Actual Behavior
Some blocks are not being translated properly. After language selection keeps with original/default language - english

### Steps to Reproduce
1st -
*Set your Chrome/Firefox to other language like Brazilian Portuguese or Spanish.
*Go to https://scratch.mit.edu/projects/editor/
*Check if menu is translated
*Go to Sensores, in case of pt-br or esp (equivalent of Sensing)
You should see something like:
image

2nd-
*Set your Chrome/Firefox to your original language - even english.
*Go to https://scratch.mit.edu/projects/editor/
*Check if menu is translated
*Don´t open the Sensing Menu
*Change the language to to Brazilian Portuguese or Spanish or anyone you want to test
*Go to Sensores, in case of pt-br or esp (equivalent of Sensing)
You should see something like:
image

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
This issue are happening with the following block keys:
`SENSING_ASK_TEXT` : 
`ScratchBlocks.ScratchMsgs.translate('SENSING_ASK_TEXT', 'What\'s your name?');`
`OPERATORS_JOIN_APPLE` :
` ScratchBlocks.ScratchMsgs.translate('OPERATORS_JOIN_APPLE', 'apple');`
`OPERATORS_JOIN_BANANA` : 
`ScratchBlocks.ScratchMsgs.translate('OPERATORS_JOIN_BANANA', 'banana');`
`OPERATORS_LETTEROF_APPLE` :
`ScratchBlocks.ScratchMsgs.translate('OPERATORS_LETTEROF_APPLE', 'a');`

### Operating System and Browser
Windows 10

### PR DESCRIPTION
**Pull request by apple502j**
### Resolves
Resolves #5445
Resolves #5489 
Resolves #2544 (this issue is tied to wrong issue)

### Proposed Changes
Adds an argument to makeToolboxXML, isInitialSetup, which is true only in reducers/toolbox.js. When true, the toolbox returned does not have blocks that have localized parameters.

### Reason for Changes
It looks like if a toolbox item is loaded while the initial setup (aka: https://github.com/LLK/scratch-gui/blob/develop/src/reducers/toolbox.js#L5 ) the translated version won't show up when loaded. This didn't happen for looks blocks' text, because during the setup `isStage` was `true` and the toolbox item for say block was not loaded.

### Test Coverage
Added a test, though it's flaky: #5462 

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [x] Chrome 
 * [x] Firefox 
 * [x] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

File: src/lib/make-toolbox-xml.js [hunk 1]
```diff
@@ -4,7 +4,7 @@ const categorySeparator = '<sep gap="36"/>';
 
 const blockSeparator = '<sep gap="36"/>'; // At default scale, about 28px
 
-const motion = function (isStage, targetId) {
+const motion = function (_, isStage, targetId) {
```
Comment (chrisgarrity) [inline src/lib/make-toolbox-xml.js:7]: I know using `_` is going to suppress eslint warnings, but I think people won't remember what the variable is for if a category ever ends up needing initial setup. I think it would be better to use `isInitialSetup` everywhere and use `// eslint-disable-line no-unused-vars` if the linter complains.

**Comment by jt-labs-pt** [comment]
Hi everyone! 🚀

Inspired by the amazing work of the @LLK team, I'm developing ScratchStation — an open-source handheld console powered by Raspberry Pi, designed specifically to bring the Scratch ecosystem into a dedicated hardware experience.

My goal is to create a seamless, 'plug-and-play' device where kids and creators can play community projects at 60 FPS (via TurboWarp) and even edit their code offline using an integrated touch-screen interface.

I’ve just published the initial roadmap and vision on GitHub. I would be honored to get any feedback, advice on performance optimization, or just a 'hello' from this community.

Check out the project here: [https://github.com/nuveration/Ultimate-Scratch-Console/]

Thanks for making creative coding possible for everyone!
