### PR TITLE
Use correct message for global list

### LINKED ISSUE #4474: Making a new list on the background say "This variable"
### Expected Behavior
Make a new list. In the dialog, it should say "This list will be available to all sprites."

### Actual Behavior
In the new list dialog, it says "This variable will be available to all sprites.". Of course, it shouldn't say "Variables", that could confuse new scratchers. However, it's a minor bug.

### Steps to Reproduce
Go to any project. 
Go to the background.
Make a new list.
Read.

### Operating System and Browser
Windows 10 and Google Chrome

### LINKED ISSUE #5184: Modal for list creation on stage says VARIABLE will be available to all sprites
### Expected Behavior

When creating a list on the stage, where there would normally be a "for all/this sprite(s)" selector it should say "This list will be available to all sprites."

### Actual Behavior

It says "This *variable* will be available to all sprites":
image

### Steps to Reproduce

1. Go to the Stage
2. Click "Make a list"
3. <br/>image

### Operating System and Browser

Windows 10 OS Version 1809 (Build 17763.737) Chrome 76.0.3809.132 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by apple502j**
### Resolves
Resolves #4474 
Closes #5184 

### Proposed Changes
There is a new prop varType to `prompt` which can be used to change text depending on the variable type. Also use that to choose the text shown when the user is creating a list on stage.

### Reason for Changes
This is list.

### CODE REVIEW

File: src/components/prompt/prompt.jsx [hunk 1]
```diff
@@ -58,9 +65,15 @@ const PromptComponent = props => (
                 <div>
                     {props.isStage ?
                         <div className={styles.infoMessage}>
-                            <FormattedMessage
-                                {...messages.availableToAllSpritesMessage}
-                            />
+                            {props.varType === SCALAR_VARIABLE_TYPE ? (
```
Comment (kchadha) [inline src/components/prompt/prompt.jsx]: It might be good to pass in a boolean prop for whether or not this is a list type instead of passing in the varType itself. That way, we don't have to import SCALAR_VARIABLE_TYPE from scratch-blocks at this level.

File: src/components/prompt/prompt.jsx [hunk 2]
```diff
@@ -141,6 +153,7 @@ PromptComponent.propTypes = {
     defaultValue: PropTypes.string,
     globalSelected: PropTypes.bool.isRequired,
     isStage: PropTypes.bool.isRequired,
+    isVariable: PropTypes.bool.isRequired,
```
Comment (kchadha) [inline src/components/prompt/prompt.jsx]:
```suggestion
    showListMessage: PropTypes.bool.isRequired,
```

File: src/containers/blocks.jsx [hunk 3]
```diff
@@ -544,6 +544,7 @@ class Blocks extends React.Component {
                     <Prompt
                         defaultValue={this.state.prompt.defaultValue}
                         isStage={vm.runtime.getEditingTarget().isStage}
+                        isVariable={this.state.prompt.varType === VMScratchBlocks.SCALAR_VARIABLE_TYPE}
```
Comment (kchadha) [inline src/containers/blocks.jsx]:
```suggestion
                        showListMessage={this.state.prompt.varType === VMScratchBlocks.LIST_VARIABLE_TYPE}
```

File: src/containers/prompt.jsx [hunk 4]
```diff
@@ -60,6 +60,7 @@ class Prompt extends React.Component {
                 defaultValue={this.props.defaultValue}
                 globalSelected={this.state.globalSelected}
                 isStage={this.props.isStage}
+                isVariable={this.props.isVariable}
```
Comment (kchadha) [inline src/containers/prompt.jsx]:
```suggestion
                showListMessage={this.props.showListMessage}
```

File: src/containers/prompt.jsx [hunk 5]
```diff
@@ -79,6 +80,7 @@ class Prompt extends React.Component {
 Prompt.propTypes = {
     defaultValue: PropTypes.string,
     isStage: PropTypes.bool.isRequired,
+    isVariable: PropTypes.bool.isRequired,
```
Comment (kchadha) [inline src/containers/prompt.jsx]:
```suggestion
    showListMessage: PropTypes.bool.isRequired,
```

File: src/components/prompt/prompt.jsx [hunk 6]
```diff
@@ -58,9 +64,15 @@ const PromptComponent = props => (
...
-                            />
+                            {props.isVariable ? (
+                                <FormattedMessage
+                                    {...messages.availableToAllSpritesMessage}
+                                />
+                            ) : (
+                                <FormattedMessage
+                                    {...messages.listAvailableToAllSpritesMessage}
+                                />
+                            )}
```
Comment (kchadha) [inline src/components/prompt/prompt.jsx]:
```suggestion
                            {props.showListMessage ? (
                                <FormattedMessage
                                    {...messages.listAvailableToAllSpritesMessage}
                                />
                            ) : (
                                <FormattedMessage
                                    {...messages.availableToAllSpritesMessage}
                                />
                            )}
```

**Review by kchadha — COMMENTED** [review]
Thank you for this PR @apple502j! I'm sorry it has taken so long to review.

I've made some suggested changes in the comments to make the new prop be named closer to what we're using it for.

File: src/containers/blocks.jsx [hunk 7]
```diff
@@ -544,6 +544,7 @@ class Blocks extends React.Component {
                     <Prompt
                         defaultValue={this.state.prompt.defaultValue}
                         isStage={vm.runtime.getEditingTarget().isStage}
+                        showListMessage={this.state.prompt.varType === VMScratchBlocks.LIST_VARIABLE_TYPE}
```
Comment (kchadha) [inline src/containers/blocks.jsx]:
```suggestion
                        showListMessage={this.state.prompt.varType === this.ScratchBlocks.LIST_VARIABLE_TYPE}
```
