### PR TITLE
Position blocks added from "share the love" within the viewport

### LINKED ISSUE #1739: Change defaults and ordering for > < = blocks
To help new learners more quickly recognize and use the > < and = operators, suggestion to add default value of 100 on the right-hand side. 
 
In addition, may help to order so that > is first (since that's used most often in projects). One suggestion is to put in the order that they are often said aloud  (at least in U.S.): > < = greater than, less than, equal to. (Currently equal to was put second to help minimize visual confusion so could order that way instead.)

### LINKED ISSUE #4270: Dropping a script from the backpack should make it appear where you drop it
### Expected Behavior

Dragging a script from the backpack and dropping it onto the code workspace should make it appear where you dropped it.

### Actual Behavior

The script shows up elsewhere (at the origin of the workspace, I think). Seriously a pain to move it somewhere more sensible..!

### Steps to Reproduce

Drag a script out of the backpack.

### Operating System and Browser

Firefox 65.0b7, Linux (Debian).

### PR DESCRIPTION
**Pull request by towerofnix**
### Resolves

Resolves LLK/scratch-vm#1739. Hopefully resolves #4270, too, but I can't test that to be certain (I don't know how to use the backpack while offline).

*(Tangentially related to #4400; I noticed while testing the repros I described [here](https://github.com/LLK/scratch-gui/issues/4400#issuecomment-462994133) that switching the sprite no longer messed with the workspace scroll while zoomed in, and it still does in scratch-gui/develop. There's still lag, presumably from generating the menu item elements, though. /cc @kchadha)*

### Proposed Changes

Takes `workspaceMetrics`, previously stored in the `<Blocks>` container's state, and changes it to be stored in global state via a reducer. Changes the `<TargetPane>` container so that, when it handles dropped blocks, it repositions them to fit within the viewport of the target sprite's workspace. (This behavior is in a new function that is also used when receiving blocks dropped from the backpack, so it should work in that case too, but I don't know how to test the backpack offline.)

### Reason for Changes

To make "share the love" (and backpacked scripts) a much more useful feature when working in large projects (sprites with lots of scripts).

### Test Coverage

Tested manually. (Would unit tests be helpful here? There's quite a bit of tweaked code, but it was mostly just simple substitutions and the typical react/redux stuff for making use of global state; and I'm not sure if the added behavior should take unit tests or not.)

### Browser Coverage

Linux Firefox, Chromium.

### CODE REVIEW

**Comment by apple502j** [comment]
Does it have something to do with 1739? It's comparing operator's issue which is already closed.

**Comment by towerofnix** [comment]
@apple502j Oh, thanks for reminding me - I was referring to an issue in a different repo. Fixed now!

**Comment by thisandagain** [comment]
@paulkaplan Bump

File: src/containers/blocks.jsx [hunk 1]
```diff
@@ -284,14 +284,17 @@ class Blocks extends React.Component {
     onWorkspaceMetricsChange () {
         const target = this.props.vm.editingTarget;
         if (target && target.id) {
-            const workspaceMetrics = Object.assign({}, this.state.workspaceMetrics, {
-                [target.id]: {
+            // Dispatch updateMetrics later, since onWorkspaceMetricsChange may be (very indirectly)
```
Comment (benjiwheeler) [inline src/containers/blocks.jsx:304]: Does this look kosher to others?

**Comment by benjiwheeler** [comment]
@chrisgarrity and I think this is now good to merge -- but we have one outstanding question.

@rschamp and @picklesrus: does the use of setTimeout here look kosher to you? https://github.com/LLK/scratch-gui/pull/4542/files#r471669610

Update: see my comment in the code

File: src/containers/blocks.jsx (hunk 1 above)
Comment (benjiwheeler) [reply src/containers/blocks.jsx:304]: Got feedback from others -- sounds like this is ok, though there is some feeling that it might not be necessary.

I assume it's necessary for the reasons @towerofnix wrote in the comment -- that you don't want to dispatch a reducer action while already handling a reducer action.

**Comment by benjiwheeler** [comment]
Thanks @towerofnix!!!!!!!
