### PR TITLE
Fix "Opening the backdrop library causes the stage backdrop editor to become selected"

### LINKED ISSUE #2188: Opening the backdrop library causes the stage backdrop editor to become selected
### Expected Behavior

_Please describe what should happen_
The backdrop editor should be selected when I choose a backdrop. If I don't do anything in the library, my place in the editor shouldn't change.

### Actual Behavior

_Describe what actually happens_
Clicking the "Choose a backdrop" button and then hitting <kbd>Esc</kbd>, leaves the editor in the Stage's paint editor tab.
add-backdrop

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
In a new project, with a sprite's code tab open, click the "Choose a backdrop" button, then hit <kbd>Esc</kbd> (or otherwise close the library without doing anything).

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
Not browser related

### PR DESCRIPTION
**Pull request by sjhuang26**
### Resolves

#2188 

### Proposed Changes

When the "choose a backdrop" button is pressed (the biggest button in the action menu) but the backdrop library is closed without selecting a backdrop, the Stage's paint editor tab is **not** opened. Instead, nothing happens.

Behind the scenes, there are several changes:
* The BackdropLibrary component is no longer nested in the CostumeTab component; it has been moved to the root GUI component, as discussed in the issue.
* Clicks on the action menu don't propagate up to the stage selector. This way, a click to the action menu won't select the stage as well.
* The third commit ("fix bug") explicitly shifts focus to the stage immediately after a backdrop is added, which is necessary.

### Browser Coverage
Check the OS/browser combinations tested (At least 2)

Mac
 * [ ] Chrome 
 * [ ] Firefox 
 * [ ] Safari
 
Windows
 * [x] Chrome 
 * [x] Firefox 
 * [ ] Edge
 
Chromebook
 * [ ] Chrome
 
iPad
* [ ] Safari

Android Tablet
* [ ] Chrome

### CODE REVIEW

File: src/components/action-menu/action-menu.jsx [hunk 1]
```diff
@@ -76,8 +76,8 @@ class ActionMenu extends React.Component {
         // (possibly slow) action is started.
         return event => {
             ReactTooltip.hide();
+            if (fn) fn(event);
```
Comment (paulkaplan) [inline src/components/action-menu/action-menu.jsx]: Why is this change made? The point of the forceHide:true => fn(event) => forceHide: false is to allow the menu to close before the (possibly long running) callback is called.
