### PR TITLE
Fixes #4253 by telling the vm the langauge when it is initialized.  B…

### LINKED ISSUE #4253: Translate extension "language" block returns "English" until you go into editor
### Expected Behavior

If your language in Scratch is set to something other than English, the "language" block in the translate extension should return that language from both the project page and editor. 

### Actual Behavior

If you view a project from the project page, the block returns "English." If you go into the editor, it will return the correct language and if you go back to the project page it will continue to return the correct language. 

### Steps to Reproduce

Switch your language to something other than English. Go to [this test project](https://scratch.mit.edu/projects/277135194/). View it from the project page-- language should be wrong. Go into editor-- language should be correct. Go back to project page-- language should be correct. 

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

### PR DESCRIPTION
**Pull request by picklesrus**
…efore it didn't get the language until the blocks component mounted.

### Resolves

Resolves #4253 

### Proposed Changes

Tells the VM the locale when initializing it.

### CODE REVIEW

**Comment by picklesrus** [comment]
Adding @kchadha @cwillisf, and @chrisgarrity because I'm not totally sure we're okay with implications of this change. Here are my questions:
1. The call to setLocale in vm will cause a call to 
extensionManager.refreshBlocks in a place where it didn't before.  In the case of calling this from player mode, that seems to work fine because refreshBlocks runs over _loadedExtensions and there are none yet. Is that something we can/should count on? And should it matter?
2.  Why does vm's setLocale always call refreshBlocks but only conditionally call formatMessage.setup when the locale has actually changed?
3. Should I conditionally call vm.setLocale from gui only when the language is changed?  I didn't, because, iiuc, the vm.inInitialized is essentially keeping track of that for me.

File: src/lib/vm-manager-hoc.jsx [hunk 1]
```diff
@@ -33,6 +33,7 @@ const vmManagerHOC = function (WrappedComponent) {
                 this.props.vm.attachAudioEngine(this.audioEngine);
                 this.props.vm.setCompatibilityMode(true);
                 this.props.vm.initialized = true;
+                this.props.vm.setLocale(this.props.locale, this.props.messages);
```
Comment (chrisgarrity) [inline src/lib/vm-manager-hoc.jsx]: This may be overkill, but you could check whether the locale is different before setting it. `this.props.vm.getLocale()` will return the current vm locale. If it doesn't match `this.props.locale`, then set it.

Comment (cwillisf) [reply src/lib/vm-manager-hoc.jsx]: IMO it would be better for `setLocale` to check internally if it's being asked to make a change, and early-out or otherwise do nothing if the new locale matches the old one. That way we only write that `if` statement in one place instead of in every place that calls `setLocale`.

Comment (picklesrus) [reply src/lib/vm-manager-hoc.jsx]: Yeah. That's why I'm curious about why vm's setLocale does some things conditionally, but always calls refreshBlocks.

Comment (chrisgarrity) [reply src/lib/vm-manager-hoc.jsx]: So checking is definitely overkill as vm does the check. There were times when the language would change and the extension blocks would end up out of sync (one language behind). I think calling refreshBlocks ensured that the extensions were always in sync. However, it does seem like we could put the refreshBlocks inside the check and not call it if the language hasn't changed.

Comment (chrisgarrity) [reply src/lib/vm-manager-hoc.jsx]: I did a quick check to see what would happen if the refreshBlocks wasn't called. When you switch from player to `see inside` the extension blocks are not rendered properly (red blocks). So even though vm is initialized, and the locale is set, we do need to refreshBlocks when switching between player and editor views. Basically, always calling refreshBlocks ensures that the extensions get rendered correctly regardless of the path to get here (load project with extension, add extension, see inside, etc)

Comment (kchadha) [reply src/lib/vm-manager-hoc.jsx]: @cwillisf, @chrisgarrity, I'm curious what your thoughts are about calling `vm.setLocale()` before or after `vm.start()`? I think it makes sense, but I want to make sure because there are not too many things we call before `vm.start()`

File: src/lib/vm-manager-hoc.jsx [hunk 2]
```diff
@@ -119,6 +122,8 @@ const vmManagerHOC = function (WrappedComponent) {
         return {
             fontsLoaded: state.scratchGui.fontsLoaded,
             isLoadingWithId: getIsLoadingWithId(loadingState),
+            locale: state.locales.locale,
```
Comment (kchadha) [inline src/lib/vm-manager-hoc.jsx]: locale and messages should also be added where we are omitting props to prevent unnecessary props from being passed down to children (in `render` between the two eslint disable comments)

Comment (picklesrus) [reply src/lib/vm-manager-hoc.jsx]: Fixed!

File: src/lib/vm-manager-hoc.jsx (hunk 1 above)
Comment (cwillisf) [reply src/lib/vm-manager-hoc.jsx]: @kchadha are you asking about theoretical principles or concrete bugs? ;)

IMO it's morally fine to call `vm.setLocale()` before `vm.start()` in that I think of the locale as a setting that can be changed at any time. You can paint your car whether or not it's moving... in fact, some would argue it's better to paint a stationary car. Those people have no sense of adventure.

In terms of whether or not it's currently safe... uh... I'm not sure, to be honest. I would expect it to be safe and I'm not aware of anything on the VM side that would make it unsafe, but I'm less familiar with the side effects on the scratch-blocks side of things. Any thoughts on that, @chrisgarrity?
