### PR TITLE
Close quotation mark

### LINKED ISSUE #3191: Quotation mark should be closed on each lines
https://github.com/LLK/scratch-gui/blob/1046ee3ab364fb62e4549fc2acfef09cb4240b8c/src/components/crash-message/crash-message.jsx#L25

I found a message with indent on Transifex.

### PR DESCRIPTION
**Pull request by apple502j**
### Resolves
Resolves #3191 
### Proposed Changes
Closes quotation mark on each line
### Reason for Changes
Transifex shows text with indent

### CODE REVIEW

File: src/components/crash-message/crash-message.jsx [hunk 1]
```diff
@@ -22,9 +22,9 @@ const CrashMessage = props => (
             </h2>
             <p>
                 <FormattedMessage
-                    defaultMessage="We are so sorry, but it looks like Scratch has crashed. This bug has been
-                        automatically reported to the Scratch Team. Please refresh your page to try
-                        again."
+                    defaultMessage={'We are so sorry, but it looks like Scratch has crashed. This bug has been' +
+                        'automatically reported to the Scratch Team. Please refresh your page to try' +
```
Comment (Kenny2github) [inline src/components/crash-message/crash-message.jsx]:
```suggestion
                        ' automatically reported to the Scratch Team. Please refresh your page to try' +
```

File: src/components/crash-message/crash-message.jsx [hunk 2]
```diff
@@ -22,9 +22,9 @@ const CrashMessage = props => (
...
+                        'again.'}
```
Comment (Kenny2github) [inline src/components/crash-message/crash-message.jsx]:
```suggestion
                        ' again.'}
```
