### PR TITLE
Nicer crash message format

### LINKED ISSUE #1205: What should GUI display if 'something terrible' happens
To handle the WebGL errors, I've added an [error boundary](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html). If the failure is WebGL it'll show the missing WebGL modal, but what should it display if something unexpected fails.

### PR DESCRIPTION
**Pull request by chrisgarrity**
### Resolves

Fixes #1205.

### Proposed Changes

Adds crash-message component to render nicer message with css when unhandled errors occur. Text is not translated to avoid cascading errors.

### Test Coverage

Normal tests run.

Temporarily changed GUI component to throw an error to generate an unhandled error. Screenshot of new message:
screen shot 2018-02-26 at 6 37 31 pm

Try to load a 1.4 project e.g. `#1234`, to generate a crash.

### CODE REVIEW

**Comment by kchadha** [comment]
@chrisgarrity This looks awesome!

Should we add additional messaging here around missing features? For example: #1390

**Comment by chrisgarrity** [comment]
@kchadha I don't think we should add 1.4 messaging to this particular screen as it suggests they `reload` the page, and reloading a 1.4 project is not going to help. However, it looks pretty easy to detect the 1.4 unhandled error in the error boundary `Uncaught SyntaxError: Unexpected token S in JSON at position 0` and show a different message with a `back` button instead.

File: src/containers/error-boundary.jsx [hunk 1]
```diff
@@ -28,21 +29,16 @@ class ErrorBoundary extends React.Component {
         window.history.back();
     }
 
+    handleReload () {
+        window.location.reload();
```
Comment (kchadha) [inline src/containers/error-boundary.jsx]: Instead of calling this here, you can call `window.location.replace(window.location.origin)` to go back to the empty project url.

**Comment by chrisgarrity** [comment]
@kchadha made that change
